
---
title: "EPIC Pipeline"
date: "01 Februar, 2018"
output:
  pdf_document:
    toc: true
    toc_depth: 2
---


This is a pipeline for preprocessing EPIC-Methylation data using R. 


## PART 1: Read data and parameters



We are working with data from directory /data/epigenetics/01_EWAS/03_psychiatric/01_PANTHER/Panther which contains $168$ idat files.
The annotationfile used is 

../annotationfileB4_2017-09-15.csv 
- if problems occur with annotation, please have a look at [Illumina downloads](https://support.illumina.com/array/downloads.html)    *Infimum Methylation EPIC Product files*. 


Output is directed to /data/epigenetics/01_EWAS/03_psychiatric/01_PANTHER/final_preprocessing/outfiles. We use samples listed in /data/epigenetics/01_EWAS/03_psychiatric/01_PANTHER/final_preprocessing/samplesfile for quality control. 

As given in *parameterfile.R*, the following parameters were used: 

parameter                     | value
------------------------------|-------------------------------------
arraytype                     | IlluminaHumanMethylationEPIC
detPthreshold                 | $10^{-16}$
callrate.thres                | $0.93$
filterOutlierCtrlQC           | TRUE
QuantileNormalize             | TRUE
InterQuartileRangeCalculation | TRUE

Further we interpret the values for the gender in the samplesfile as **1=female** and **0=male**. 


```
## The samples listed in /data/epigenetics/01_EWAS/03_psychiatric/01_PANTHER/final_preprocessing/samplesfile are used for quantile normalization 
##  and calculation of outliers regarding inter-quartile-range.
```


* PCA is conducted to get controlprobe scores. 



* Detection p-values are calculated and illustrated in the following plots. Low p-values indicate that the signal is unlikely to be background noise. 

![](/dsk/data1/epigenetics/01_EWAS/03_psychiatric/01_PANTHER/final_preprocessing/2018-02-01-11h17m-Panther_files/figure-latex/unnamed-chunk-11-1.pdf)<!-- --> 





![](/dsk/data1/epigenetics/01_EWAS/03_psychiatric/01_PANTHER/final_preprocessing/2018-02-01-11h17m-Panther_files/figure-latex/unnamed-chunk-12-1.pdf)<!-- --> 
\pagebreak


The following table summarizes how many detection p-values are smaller than the threshold $10^{-16}$ given in the *parameterfile*, or 0.01: 

 threshold           | count                                       | percentage
---------------------|---------------------------------------------|-----------------------------------------------------
$10^{-16}$ | $143282913$    | $0.9838937$
0.01                 | $144881923$             | $0.9948738$



  



* The probes are divided by chromosome type: autosomal probes, chromosome X probes and chromosome Y probes.
$143282913$   ($0.984$ \%)   measurements are excluded because their detection p-value is strictly smaller than $10^{-16}$. 
To skip this filtering, set the parameter *detPthreshold* to a value **strictly** bigger than 1 in the *parameterfile.R*.

* The data is divided into automomal chromosomes and gametes to calculate call rates and separate sets of beta values.



beta values:   | autosomes           |  sex chromosomes 
---------------|---------------------|----------------------------
dimension:     | $846232, 168$ | $19627, 168$




## PART 2 : lowlevel QC

The quality control consists of three parts: 

1. There is call-rate filtering with threshold $0.93$
2. The second part is based on control probes. Details are given in the [ILMN HD methylation assay protocol guide (15019519)](https://support.illumina.com/downloads/infinium_hd_methylation_assay_protocol_guide_(15019519_b).html).
3. The data is checked for sex mismatch. 




$166$ samples are included in the analysis, identified by the samplefile and existing sample calls:


```
##   [1] "DOMPA004A" "DOMPA004C" "DOMKO020A" "DOMPA007A" "DOMPA007C"
##   [6] "DOMKO057A" "DOMPA001A" "DOMKO021A" "DOMPA008A" "DOMPA008C"
##  [11] "DOMKO030A" "DOMPA009A" "DOMPA009C" "DOMKO063A" "DOMPA002A"
##  [16] "DOMKO046A" "DOMPA010A" "DOMPA010C" "DOMKO023A" "DOMPA011A"
##  [21] "DOMPA011C" "DOMKO012A" "DOMPA003A" "DOMKO065A" "DOMPA012A"
##  [26] "DOMPA012C" "DOMKO050A" "DOMPA013A" "DOMPA013C" "DOMKO042A"
##  [31] "DOMPA046A" "DOMKO002A" "DOMPA014A" "DOMPA014C" "DOMKO032A"
##  [36] "DOMPA015A" "DOMPA015C" "DOMKO062A" "DOMPA054A" "DOMKO049A"
##  [41] "DOMPA016A" "DOMPA016C" "DOMKO011A" "DOMPA017A" "DOMPA017C"
##  [46] "DOMKO047A" "DOMPA058A" "DOMKO054A" "DOMPA018A" "DOMPA018C"
##  [51] "DOMKO009A" "DOMPA019A" "DOMPA019C" "DOMKO018A" "DOMPA020A"
##  [56] "DOMPA020C" "DOMKO033A" "DOMPA021A" "DOMPA021C" "DOMKO060A"
##  [61] "DOMPA022A" "DOMPA022C" "DOMKO048A" "DOMKO003A" "DOMKO034A"
##  [66] "DOMPA024A" "DOMPA024C" "DOMKO058A" "DOMPA025A" "DOMPA025C"
##  [71] "DOMPA026A" "DOMPA026C" "DOMKO051A" "DOMPA027A" "DOMPA027C"
##  [76] "DOMKO008A" "DOMPA028A" "DOMPA028C" "DOMKO006A" "DOMPA029A"
##  [81] "DOMPA029C" "DOMKO010A" "DOMPA030A" "DOMPA030C" "DOMKO029A"
##  [86] "DOMKO044A" "DOMPA031A" "DOMPA031C" "DOMKO025A" "DOMPA032A"
##  [91] "DOMPA032C" "DOMKO014A" "DOMPA033A" "DOMPA033C" "DOMPA034A"
##  [96] "DOMPA034C" "DOMKO031A" "DOMPA036A" "DOMPA036C" "DOMKO064A"
## [101] "DOMPA037A" "DOMPA037C" "DOMKO055A" "DOMPA038A" "DOMPA038C"
## [106] "DOMKO004A" "DOMPA039A" "DOMPA039C" "DOMKO027A" "DOMKO005A"
## [111] "DOMPA040A" "DOMPA040C" "DOMPA041A" "DOMPA041C" "DOMKO028A"
## [116] "DOMPA042A" "DOMPA042C" "DOMKO052A" "DOMPA043A" "DOMPA043C"
## [121] "DOMKO040A" "DOMPA044A" "DOMPA044C" "DOMKO043A" "DOMPA045A"
## [126] "DOMPA045C" "DOMKO036A" "DOMPA047A" "DOMPA047C" "DOMKO038A"
## [131] "DOMPA048A" "DOMPA048C" "DOMKO024A" "DOMKO022A" "DOMPA049A"
## [136] "DOMPA049C" "DOMPA050A" "DOMPA050C" "DOMKO026A" "DOMPA051A"
## [141] "DOMPA051C" "DOMKO035A" "DOMPA052A" "DOMPA052C" "DOMKO056A"
## [146] "DOMPA053A" "DOMPA053C" "DOMKO059A" "DOMPA055A" "DOMPA055C"
## [151] "DOMKO041A" "DOMPA056A" "DOMPA056C" "DOMKO045A" "DOMPA057A"
## [156] "DOMPA057C" "DOMKO039A" "DOMKO013A" "DOMPA059A" "DOMPA059C"
## [161] "DOMPA061A" "DOMPA061C" "DOMKO016A" "DOMKO017A" "DOMKO015A"
## [166] "DOMKO061A"
```


  

* $0$ samples were tagged for exclusion because the call-rate was below the threshold $0.93$.




The first 3 rows of control probes information from QC contain the following information:


```
##                      Cgreen     Cred Ugreen     Ured BSIIgreen BSIIred
## 200973410156_R01C01 11128.5 15990.33  396.0 746.6667    621.75 11406.0
## 200991630056_R05C01 10047.5 13852.00  392.5 678.6667    513.00 10194.0
## 200973410156_R02C01 12927.0 18171.67  457.0 853.3333    717.00 13790.5
##                      HybH HybL  TR SpecIPMred SpecIPMgreen SpecIMMred
## 200973410156_R01C01 24111 7669 137   6029.167     2332.333   333.8333
## 200991630056_R05C01 21875 6616 107   4994.333     2349.000   308.0000
## 200973410156_R02C01 27046 8295 192   6751.500     2963.167   407.8333
##                     SpecIMMgreen SpecIIspec SpecIIunspec   ExtCG ExtAT
## 200973410156_R01C01     80.83333   15850.67     260.3333 25819.0 33705
## 200991630056_R05C01     86.83333   12859.67     212.0000 24346.5 36603
## 200973410156_R02C01    124.66667   17133.33     307.0000 30377.5 40598
##                     StainingRedH StainingGreenH StainingRedB
## 200973410156_R01C01        32045          20467          463
## 200991630056_R05C01        27154          17398          583
## 200973410156_R02C01        39497          22626          559
##                     StainingGreenB
## 200973410156_R01C01            197
## 200991630056_R05C01            115
## 200973410156_R02C01            156
```

In the following control probes are checked. For a more detailed descriptin see e.g. the [ILMN HD methylation assay protocol guide (15019519)](https://support.illumina.com/downloads/infinium_hd_methylation_assay_protocol_guide_(15019519_b).html) or the [Illumina BeadArray Controls Reporter Software Guide ](https://support.illumina.com/downloads/beadarray-controls-reporter-software-guide-1000000004009.html),pages 6-8. Probes are evaluated by MA plots. BS-I and BS-II control probes check the DNA bisulfite conversion step.

![](/dsk/data1/epigenetics/01_EWAS/03_psychiatric/01_PANTHER/final_preprocessing/2018-02-01-11h17m-Panther_files/figure-latex/unnamed-chunk-21-1.pdf)<!-- --> ![](/dsk/data1/epigenetics/01_EWAS/03_psychiatric/01_PANTHER/final_preprocessing/2018-02-01-11h17m-Panther_files/figure-latex/unnamed-chunk-21-2.pdf)<!-- --> ![](/dsk/data1/epigenetics/01_EWAS/03_psychiatric/01_PANTHER/final_preprocessing/2018-02-01-11h17m-Panther_files/figure-latex/unnamed-chunk-21-3.pdf)<!-- --> 

We also check the Hybridisation of the amplified DNA to the array:

![](/dsk/data1/epigenetics/01_EWAS/03_psychiatric/01_PANTHER/final_preprocessing/2018-02-01-11h17m-Panther_files/figure-latex/unnamed-chunk-22-1.pdf)<!-- --> ![](/dsk/data1/epigenetics/01_EWAS/03_psychiatric/01_PANTHER/final_preprocessing/2018-02-01-11h17m-Panther_files/figure-latex/unnamed-chunk-22-2.pdf)<!-- --> ![](/dsk/data1/epigenetics/01_EWAS/03_psychiatric/01_PANTHER/final_preprocessing/2018-02-01-11h17m-Panther_files/figure-latex/unnamed-chunk-22-3.pdf)<!-- --> ![](/dsk/data1/epigenetics/01_EWAS/03_psychiatric/01_PANTHER/final_preprocessing/2018-02-01-11h17m-Panther_files/figure-latex/unnamed-chunk-22-4.pdf)<!-- --> ![](/dsk/data1/epigenetics/01_EWAS/03_psychiatric/01_PANTHER/final_preprocessing/2018-02-01-11h17m-Panther_files/figure-latex/unnamed-chunk-22-5.pdf)<!-- --> ![](/dsk/data1/epigenetics/01_EWAS/03_psychiatric/01_PANTHER/final_preprocessing/2018-02-01-11h17m-Panther_files/figure-latex/unnamed-chunk-22-6.pdf)<!-- --> ![](/dsk/data1/epigenetics/01_EWAS/03_psychiatric/01_PANTHER/final_preprocessing/2018-02-01-11h17m-Panther_files/figure-latex/unnamed-chunk-22-7.pdf)<!-- --> ![](/dsk/data1/epigenetics/01_EWAS/03_psychiatric/01_PANTHER/final_preprocessing/2018-02-01-11h17m-Panther_files/figure-latex/unnamed-chunk-22-8.pdf)<!-- --> ![](/dsk/data1/epigenetics/01_EWAS/03_psychiatric/01_PANTHER/final_preprocessing/2018-02-01-11h17m-Panther_files/figure-latex/unnamed-chunk-22-9.pdf)<!-- --> 


The following table lists the detected outliers identified by the quality control and can be found 
in the file /data/epigenetics/01_EWAS/03_psychiatric/01_PANTHER/final_preprocessing/outfiles/samples-filtered.csv in a slightly expanded version. 


```
##   Sample_Name                                                filter
## 1   DOMPA019C Staining Green (cross-check with Extension outliers!)
## 2   DOMPA042A Staining Green (cross-check with Extension outliers!)
##                sample        x        y Sample_Well   Sample_Plate
## 1 201096090135_R05C01 8.345934 12.04798         E07 WG5121691-MSA4
## 2 201105900157_R06C01 8.175125 12.35021         F03 WG5121692-MSA4
##   Sample_Group Pool_ID Gender  callrate
## 1           53      NA      0 0.9939969
## 2          118      NA      1 0.9981979
```

Gamete methylation can be used to check sex mismatches. First, we see the loadings of the PCA on markers in the space of samples. The second plot shows the principle components of the PCA on the samples in the space of samples.

![](/dsk/data1/epigenetics/01_EWAS/03_psychiatric/01_PANTHER/final_preprocessing/2018-02-01-11h17m-Panther_files/figure-latex/unnamed-chunk-24-1.pdf)<!-- --> ![](/dsk/data1/epigenetics/01_EWAS/03_psychiatric/01_PANTHER/final_preprocessing/2018-02-01-11h17m-Panther_files/figure-latex/unnamed-chunk-24-2.pdf)<!-- --> 


![](/dsk/data1/epigenetics/01_EWAS/03_psychiatric/01_PANTHER/final_preprocessing/2018-02-01-11h17m-Panther_files/figure-latex/unnamed-chunk-25-1.pdf)<!-- --> ![](/dsk/data1/epigenetics/01_EWAS/03_psychiatric/01_PANTHER/final_preprocessing/2018-02-01-11h17m-Panther_files/figure-latex/unnamed-chunk-25-2.pdf)<!-- --> 


![](/dsk/data1/epigenetics/01_EWAS/03_psychiatric/01_PANTHER/final_preprocessing/2018-02-01-11h17m-Panther_files/figure-latex/unnamed-chunk-26-1.pdf)<!-- --> 

![](/dsk/data1/epigenetics/01_EWAS/03_psychiatric/01_PANTHER/final_preprocessing/2018-02-01-11h17m-Panther_files/figure-latex/unnamed-chunk-27-1.pdf)<!-- --> 
  

$4$ of all sample call rates are lower than 0.98,  
 and $0$ are lower than the threshold $0.93$.

![](/dsk/data1/epigenetics/01_EWAS/03_psychiatric/01_PANTHER/final_preprocessing/2018-02-01-11h17m-Panther_files/figure-latex/unnamed-chunk-28-1.pdf)<!-- --> 
  

$4.5519\times 10^{4}$ of all marker call rates are lower than 0.98,  
 and $23127$ are lower than the threshold 0.95.



The previous calculations provide all information needed to filter the samples and make a tab-separated file *samplesfilefinal* for further use. 
For this analysis, /data/epigenetics/01_EWAS/03_psychiatric/01_PANTHER/final_preprocessing/samplesfile was used as list of samples for the final preprocessing steps. 

![](/dsk/data1/epigenetics/01_EWAS/03_psychiatric/01_PANTHER/final_preprocessing/2018-02-01-11h17m-Panther_files/figure-latex/unnamed-chunk-29-1.pdf)<!-- --> 
  



## PART 3: Quantile Normalisation


166 samples are included in the analysis, identified by the *samplesfilefinal* /data/epigenetics/01_EWAS/03_psychiatric/01_PANTHER/final_preprocessing/samplesfile and existing sample calls:


```
##   [1] "DOMPA004A" "DOMPA004C" "DOMKO020A" "DOMPA007A" "DOMPA007C"
##   [6] "DOMKO057A" "DOMPA001A" "DOMKO021A" "DOMPA008A" "DOMPA008C"
##  [11] "DOMKO030A" "DOMPA009A" "DOMPA009C" "DOMKO063A" "DOMPA002A"
##  [16] "DOMKO046A" "DOMPA010A" "DOMPA010C" "DOMKO023A" "DOMPA011A"
##  [21] "DOMPA011C" "DOMKO012A" "DOMPA003A" "DOMKO065A" "DOMPA012A"
##  [26] "DOMPA012C" "DOMKO050A" "DOMPA013A" "DOMPA013C" "DOMKO042A"
##  [31] "DOMPA046A" "DOMKO002A" "DOMPA014A" "DOMPA014C" "DOMKO032A"
##  [36] "DOMPA015A" "DOMPA015C" "DOMKO062A" "DOMPA054A" "DOMKO049A"
##  [41] "DOMPA016A" "DOMPA016C" "DOMKO011A" "DOMPA017A" "DOMPA017C"
##  [46] "DOMKO047A" "DOMPA058A" "DOMKO054A" "DOMPA018A" "DOMPA018C"
##  [51] "DOMKO009A" "DOMPA019A" "DOMPA019C" "DOMKO018A" "DOMPA020A"
##  [56] "DOMPA020C" "DOMKO033A" "DOMPA021A" "DOMPA021C" "DOMKO060A"
##  [61] "DOMPA022A" "DOMPA022C" "DOMKO048A" "DOMKO003A" "DOMKO034A"
##  [66] "DOMPA024A" "DOMPA024C" "DOMKO058A" "DOMPA025A" "DOMPA025C"
##  [71] "DOMPA026A" "DOMPA026C" "DOMKO051A" "DOMPA027A" "DOMPA027C"
##  [76] "DOMKO008A" "DOMPA028A" "DOMPA028C" "DOMKO006A" "DOMPA029A"
##  [81] "DOMPA029C" "DOMKO010A" "DOMPA030A" "DOMPA030C" "DOMKO029A"
##  [86] "DOMKO044A" "DOMPA031A" "DOMPA031C" "DOMKO025A" "DOMPA032A"
##  [91] "DOMPA032C" "DOMKO014A" "DOMPA033A" "DOMPA033C" "DOMPA034A"
##  [96] "DOMPA034C" "DOMKO031A" "DOMPA036A" "DOMPA036C" "DOMKO064A"
## [101] "DOMPA037A" "DOMPA037C" "DOMKO055A" "DOMPA038A" "DOMPA038C"
## [106] "DOMKO004A" "DOMPA039A" "DOMPA039C" "DOMKO027A" "DOMKO005A"
## [111] "DOMPA040A" "DOMPA040C" "DOMPA041A" "DOMPA041C" "DOMKO028A"
## [116] "DOMPA042A" "DOMPA042C" "DOMKO052A" "DOMPA043A" "DOMPA043C"
## [121] "DOMKO040A" "DOMPA044A" "DOMPA044C" "DOMKO043A" "DOMPA045A"
## [126] "DOMPA045C" "DOMKO036A" "DOMPA047A" "DOMPA047C" "DOMKO038A"
## [131] "DOMPA048A" "DOMPA048C" "DOMKO024A" "DOMKO022A" "DOMPA049A"
## [136] "DOMPA049C" "DOMPA050A" "DOMPA050C" "DOMKO026A" "DOMPA051A"
## [141] "DOMPA051C" "DOMKO035A" "DOMPA052A" "DOMPA052C" "DOMKO056A"
## [146] "DOMPA053A" "DOMPA053C" "DOMKO059A" "DOMPA055A" "DOMPA055C"
## [151] "DOMKO041A" "DOMPA056A" "DOMPA056C" "DOMKO045A" "DOMPA057A"
## [156] "DOMPA057C" "DOMKO039A" "DOMKO013A" "DOMPA059A" "DOMPA059C"
## [161] "DOMPA061A" "DOMPA061C" "DOMKO016A" "DOMKO017A" "DOMKO015A"
## [166] "DOMKO061A"
```



Of the persons from whom samples are processed, 126 are women and 40 men.   



![](/dsk/data1/epigenetics/01_EWAS/03_psychiatric/01_PANTHER/final_preprocessing/2018-02-01-11h17m-Panther_files/figure-latex/unnamed-chunk-33-1.pdf)<!-- --> 


For the following PCA markers which had at least one cpg site missing were excluded.

![](/dsk/data1/epigenetics/01_EWAS/03_psychiatric/01_PANTHER/final_preprocessing/2018-02-01-11h17m-Panther_files/figure-latex/unnamed-chunk-34-1.pdf)<!-- --> 
  

The following plot is a PCA on **variables**: It presents the importance of samples when differentiating between the CpG sites in the best way possible. 

![](/dsk/data1/epigenetics/01_EWAS/03_psychiatric/01_PANTHER/final_preprocessing/2018-02-01-11h17m-Panther_files/figure-latex/unnamed-chunk-35-1.pdf)<!-- --> 
  


The next plot presents a PCA on **samples**, as it is more common. It shows the variance of the samples on the PC axes. 

![](/dsk/data1/epigenetics/01_EWAS/03_psychiatric/01_PANTHER/final_preprocessing/2018-02-01-11h17m-Panther_files/figure-latex/unnamed-chunk-36-1.pdf)<!-- --> ![](/dsk/data1/epigenetics/01_EWAS/03_psychiatric/01_PANTHER/final_preprocessing/2018-02-01-11h17m-Panther_files/figure-latex/unnamed-chunk-36-2.pdf)<!-- --> 
  



![](/dsk/data1/epigenetics/01_EWAS/03_psychiatric/01_PANTHER/final_preprocessing/2018-02-01-11h17m-Panther_files/figure-latex/unnamed-chunk-37-1.pdf)<!-- --> 
  



![](/dsk/data1/epigenetics/01_EWAS/03_psychiatric/01_PANTHER/final_preprocessing/2018-02-01-11h17m-Panther_files/figure-latex/unnamed-chunk-38-1.pdf)<!-- --> 

  

![](/dsk/data1/epigenetics/01_EWAS/03_psychiatric/01_PANTHER/final_preprocessing/2018-02-01-11h17m-Panther_files/figure-latex/unnamed-chunk-39-1.pdf)<!-- --> ![](/dsk/data1/epigenetics/01_EWAS/03_psychiatric/01_PANTHER/final_preprocessing/2018-02-01-11h17m-Panther_files/figure-latex/unnamed-chunk-39-2.pdf)<!-- --> 


![](/dsk/data1/epigenetics/01_EWAS/03_psychiatric/01_PANTHER/final_preprocessing/2018-02-01-11h17m-Panther_files/figure-latex/unnamed-chunk-40-1.pdf)<!-- --> 



## PART 4: Calculating Inter Quartile Ranges 

The inter-quartile range of a set of values is the difference between its 0.75-quartile and its 0.25-quartile. 
In the following, these quartiles are calculated for all autosomal beta values per probe and beta values whose difference to the median is greater than 3 times the inter-quartile range are marked as outliers and set to missing (NA) in beta.QN.all.3IQR.




part                    | number of probes                                        | percentage 
------------------------|---------------------------------------------------------|-------------------------------------------------------------------------------------------
total                   | 143732594                     | 100\%
noCall                  | 1115473            |0.0077608
noCall with filter 3IQR | 1768563  | 0.0123045

![](/dsk/data1/epigenetics/01_EWAS/03_psychiatric/01_PANTHER/final_preprocessing/2018-02-01-11h17m-Panther_files/figure-latex/unnamed-chunk-42-1.pdf)<!-- --> 
  

![](/dsk/data1/epigenetics/01_EWAS/03_psychiatric/01_PANTHER/final_preprocessing/2018-02-01-11h17m-Panther_files/figure-latex/unnamed-chunk-43-1.pdf)<!-- --> 
  

![](/dsk/data1/epigenetics/01_EWAS/03_psychiatric/01_PANTHER/final_preprocessing/2018-02-01-11h17m-Panther_files/figure-latex/unnamed-chunk-44-1.pdf)<!-- --> 

## Output



1. The following data is included in the Rdata-file QC_data_Panther_2018-02-01-11h17m.Rdata:
\begin{description}
	\item[ctrl.all, ctrl.complete.Red.all, ctrl.complete.Green.all, control.info] control probe data
	\item[ctrlprobes.scores] rotated control probe intensities into the coordinates given by principal component analysis
	\item[dp.all] detection p-values of unfiltered idat data
	\item[TypeII.Red.All etc] list the corresponding intensity values
	\item[TypeII.Red.All.d etc] list the corresponding intensity values where detection p-values smaller than threshold $10^{-16}$ are set to missing (NA).
	\item[sample.call] the sample call rates
	\item[marker.call] the marker call rates
	\item[beta.raw] the $\beta$ values calculated for autosomal probes with detection p value filter only
	\item[beta.raw.sex] the $\beta$ values calculated for sex chromosome probes with detection p value filter only
	\item[pcaAuto] output of function prcomp conducting PCA of \textbf{betaQN}
	\item[sample.callY, sample.callX] sample call rates for chromosomes X and Y for quantile normalized filtered samples
	\item[marker.call.all] marker callrate of all quantile normalized samples incl. the ones excluded by IQR-filter 
	\item[marker.outlier.all] data frame of number of probes, detected outliers and marker callrate after filtering by IQR 
\end{description}


2. The data needed for further analysis is saved as analysis_ready_Panther_2018-02-01-11h17m.Rdata:
\begin{description}
	\item[pcaControls] output of function prcomp conducting the PCA of control probes 
	\item[betaQN] $\beta$ values calculated for autosomal probes of filtered samples with quantile normalization applied 
	\item[betaQN.sex] $\beta$ values calculated for sex chromosome probes of filtered samples with quantile normalization applied 
	\item[betaQN.all] combines \textbf{betaQN} and \textbf{betaQN.sex} 
	\item[betaQN.all.3IQR] modified \textbf{betaQN.all}: IQR outliers are filtered out
	\item[mdata] transposed \textbf{betaQN} with Sample Names assigned as rownames
	\item[mdata.3IQR] transposed \textbf{betaQN.all.3IQR} with Sample Names as rownames
\end{description}

If you run the pipeline a second time the data files will be overwritten, so please store them at a different place if you want to keep both. 







## Memory load and processing time

The maximum memory load in this run was $1.95213\times 10^{4}$ Mb .
It took 1.289058 days of processing time.


## Methods

We will draft an example methods part for papers.
(in the processing)

## Credits

The code for this pipeline was written by Benjamin Lehne (Imperial College London) and Alexander Drong (Oxford University), extended by Alexander Teumer (University Medicine Greifswald/ Erasmus MC Rotterdam) and combined into the pipeline by Pascal Schlosser and Franziska Grundner-Culemann in 2017. 

See *A coherent approach for analysis of the Illumina HumanMethylation450 Bead Chip improves quality and performance in epigenome-wide association studies* by Lehne et. al., Genome Biology (2015)
for the basic idea. The method was then extended to EPIC arrays. 
Please cite this article in your publication. 
